DELIMITER |

CREATE TRIGGER after_insert_stock AFTER INSERT

ON GESTIONSTOCK FOR EACH ROW

BEGIN

    IF (NEW.TYPEGEST=1) THEN
        UPDATE PRODUIT SET QUANTITE=QUANTITE+NEW.QUANTITE WHERE CODEPRODUIT=NEW.CODEPRODUIT;
    ELSE
        UPDATE PRODUIT SET QUANTITE=QUANTITE-NEW.QUANTITE WHERE CODEPRODUIT=NEW.CODEPRODUIT;
    END IF;

END |
DELIMITER ;